import numpy as np;
numbers = np.array(range(1, 11), copy=True)
print(numbers)
ones = np.ones([2, 4], dtype=np.float64)
print(ones)
zeros = np.zeros([2, 4], dtype=np.float64)
print(zeros)
empty = np.empty([2, 4], dtype=np.float64)
print(empty)
print(ones.shape)
print(numbers.ndim)
print(zeros.dtype)
eye=np.eye(3, k=1)
print(eye)
np_numbers = np.arange(2, 5, 0.25)
print(np_numbers)
np_inumbers = np_numbers.astype(np.int)
print(np_inumbers)
sap = np.array(["MMM", "ABT", "ABBV", "ACN", "ACE", "ATVI", "ADBE", "ADT"])
print(sap)
sap2d = sap.reshape(2, 4)
print(sap2d)
sap3d = sap.reshape(2, 2, 2)
print(sap3d)
print(sap2d.T)
print(sap3d.swapaxes(1, 2))
print(sap3d.transpose(0, 2, 1))
